"""Build and execute notebooks/full_showcase.ipynb.

Purpose: a single, real, end-to-end run of Techna on a real ticker, with every
output (terminal panel, all 17 charts, JSON findings, live pytest run) baked
in as ACTUAL executed cell output -- so the artifact is self-contained and
portable (unlike the `techna.py --notebook` flag's output, which uses
relative markdown image links and breaks if the .ipynb is shared without its
sibling PNGs sitting next to it).

This notebook demonstrates BREADTH (the whole tool working end-to-end on one
real ticker) and complements notebooks/proof_of_correctness.ipynb, which
demonstrates DEPTH (individual indicator math cross-checked against a
third-party library). Neither recomputes what the other already proved.

Usage:
    python tools/build_showcase_notebook.py
"""
from __future__ import annotations

from pathlib import Path

import nbformat as nbf
from nbclient import NotebookClient

ROOT = Path(__file__).resolve().parent.parent
OUT_PATH = ROOT / "notebooks" / "full_showcase.ipynb"
SHOWCASE_TICKER = "AAPL"

nb = nbf.v4.new_notebook()
cells = []


def md(text: str) -> None:
    cells.append(nbf.v4.new_markdown_cell(text))


def code(text: str) -> None:
    cells.append(nbf.v4.new_code_cell(text))


# --------------------------------------------------------------------------- #
md(
    f"""\
# Techna — Full Showcase (end-to-end, {SHOWCASE_TICKER})

**Purpose:** a single real run of Techna's full pipeline, with every output
baked in as *actually executed* cell output — the terminal dashboard, all 17
generated charts, every module's plain-English `finding`, and a live test
suite run. This demonstrates the tool working end-to-end on real data, for
anyone viewing this file standalone (no sibling files required — every
image below is embedded directly in this notebook, not linked by path).

> **This complements, and does not replace, two other correctness artifacts:**
> - `notebooks/proof_of_correctness.ipynb` — cross-checks individual
>   indicator math (RSI/MACD/Bollinger/ADX) against an independent
>   third-party library and known-answer test cases. This notebook does
>   not re-verify that math; it demonstrates the complete tool working.
> - The offline pytest suite (150+ tests) — the actual, continuously
>   enforced correctness gate. This notebook's live test-suite cell reports
>   its result but is not a substitute for running it in CI.
>
> Generated by `tools/build_showcase_notebook.py` (re-run to refresh with
> live data; requires network access + `pip install -r requirements-notebook.txt`)."""
)

# --------------------------------------------------------------------------- #
md("## 1. Run Techna end-to-end on a real ticker")
code(
    """\
import sys
from pathlib import Path

ROOT = Path.cwd()
if not (ROOT / "techna").exists():
    ROOT = ROOT.parent
sys.path.insert(0, str(ROOT))

import importlib.util
_spec = importlib.util.spec_from_file_location("techna_cli", str(ROOT / "techna.py"))
techna_cli = importlib.util.module_from_spec(_spec)
sys.modules["techna_cli"] = techna_cli
_spec.loader.exec_module(techna_cli)

from rich.console import Console

TICKER = "AAPL"
OUT_DIR = ROOT / "notebooks" / "_showcase_output"
OUT_DIR.mkdir(parents=True, exist_ok=True)

console = Console(record=True, width=110)
exit_code = techna_cli.run(
    TICKER,
    no_interactive=True,
    explain=True,
    out_dir=str(OUT_DIR),
    console=console,
)
print(f"exit code: {exit_code}")
assert exit_code == 0, "Techna run failed -- showcase notebook cannot proceed\""""
)

# --------------------------------------------------------------------------- #
md("## 2. Terminal dashboard (as the user actually sees it)")
code(
    """\
terminal_output = console.export_text(styles=False)
print(terminal_output)"""
)

# --------------------------------------------------------------------------- #
md(
    """\
## 3. Every module's plain-English finding (from the JSON sidecar)

These sentences are produced by the same functions that write the markdown
report (Phase 25's single-source `finding` fields) -- not reimplemented or
paraphrased here."""
)
code(
    """\
import json

result = json.loads((OUT_DIR / f"{TICKER}_result.json").read_text(encoding="utf-8"))
print(f"Overall status: {result['status']}\\n")
for m in result["modules"]:
    print(f"[{m['module']:12}] {m['metrics'].get('finding', '(no finding)')}")"""
)

# --------------------------------------------------------------------------- #
md(
    """\
## 4. All 17 generated charts, each with the exact code that drew it

Every chart Techna produced for this run, embedded directly (not linked by path
-- these are real pixels baked into this .ipynb file). Immediately above each
image is the **live source** of the `report_builder.draw_*_chart` function that
drew it, fetched with `inspect.getsource()` at notebook-build time -- not
copy-pasted, so it can never silently go stale relative to the real code."""
)
code(
    """\
import inspect
from IPython.display import Image, display
from techna import report_builder

chart_suffixes = [
    "overview", "momentum", "regime", "candles", "levels", "baserates",
    "relative", "seasonality", "volume", "correlogram", "distribution",
    "52week", "drawdown", "beta", "structural_breaks", "hurst", "quantile_beta",
]
chart_files = [OUT_DIR / f"{TICKER}_{suffix}.png" for suffix in chart_suffixes]
existing = [p for p in chart_files if p.exists()]
print(f"{len(existing)} / {len(chart_files)} expected charts found.")"""
)
for _suffix in [
    "overview", "momentum", "regime", "candles", "levels", "baserates",
    "relative", "seasonality", "volume", "correlogram", "distribution",
    "52week", "drawdown", "beta", "structural_breaks", "hurst", "quantile_beta",
]:
    _fn_name = f"draw_{_suffix}_chart"
    md(f"### `{SHOWCASE_TICKER}_{_suffix}.png`")
    code(
        f"""\
print(inspect.getsource(report_builder.{_fn_name}))"""
    )
    code(
        f"""\
p = OUT_DIR / f"{{TICKER}}_{_suffix}.png"
display(Image(filename=str(p))) if p.exists() else print("(chart not generated for this run)")"""
    )

# --------------------------------------------------------------------------- #
md("## 5. Live test suite run")
code(
    """\
import subprocess

test_result = subprocess.run(
    [sys.executable, "-m", "pytest", "-q"],
    cwd=str(ROOT),
    capture_output=True,
    text=True,
)
print(test_result.stdout[-1500:])
print(f"\\npytest exit code: {test_result.returncode}")"""
)

# --------------------------------------------------------------------------- #
md(
    f"""\
## 6. Summary

| What | Result |
|---|---|
| End-to-end run on a real ticker ({SHOWCASE_TICKER}) | see Section 1 |
| Terminal dashboard | see Section 2 |
| Plain-English finding per module (11 modules) | see Section 3 |
| Charts generated | see Section 4 (embedded, standalone-portable) |
| Offline test suite | see Section 5 |

For independent verification of the underlying indicator *math* (not just
that the tool runs), see `notebooks/proof_of_correctness.ipynb`."""
)

nb["cells"] = cells

OUT_PATH.parent.mkdir(parents=True, exist_ok=True)

client = NotebookClient(
    nb,
    timeout=600,
    kernel_name="techna-py3",
    resources={"metadata": {"path": str(ROOT)}},
)
client.execute()

with open(OUT_PATH, "w", encoding="utf-8") as f:
    nbf.write(nb, f)

print(f"Wrote executed notebook -> {OUT_PATH}")
